version: '3.8'

services:
  bot:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
      - redis

  redis:
    image: redis:5-alpine
    restart: on-failure
    volumes:
        - redis-data:/data

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: on-failure


volumes:
  postgres-data:
  redis-data: